full <- lm(MaxVO2ML ~ Gender+Age1+BMI+MPH+HR+RPE+ga+gb+gm+gh+gr+ab+am+ah+ar+bm+bh+br+mh+mr+hrp,data=vo2)
step(full)
fit1 <- lm(MaxVO2ML ~ Gender+BMI+MPH+RPE+gb+gh+gr+ab+am+ar+br+mr,data=vo2)
summary(fit1)
step(full,k=5)
fit2 <- lm(MaxVO2ML ~ Gender+BMI+gh+ab+ar+mr,data=vo2)
summary(fit2)
nms <- c('gen','age','bmi','mph','hr','rpe','ga','gb','gm','gh','gr','ab','am','ah','ar','bm','bh','br','mh','mr','hrp')
library(leaps)
leaps(vo2[,c(2:7,9:23)],vo2[,8],nbest=1,names=nms)
fit3 <- lm(MaxVO2ML ~ Gender+BMI+gb+gh+ab+ar+mr,data=vo2)
summary(fit3)
fit4 <- lm(MaxVO2ML ~ Gender+Age1+BMI+MPH+HR+RPE,data=vo2)
summary(fit4)
fitclass <- lm(MaxVO2ML ~ Gender+MPH+HR+BMI+RPE+MPH*HR,data=vo2)
summary(fitclass)
library(BayesVarSel)
Bvs(formula=MaxVO2ML ~ Gender+Age1+BMI+MPH+HR+RPE+ga+gb+gm+gh+gr+ab+am+ah+ar+bm+bh+br+mh+mr+hrp,data=vo2)
fit5 <- lm(MaxVO2ML ~ Gender + MPH + bh, data=vo2)
summary(fit5)
fit6 <- lm(MaxVO2ML ~ Gender+BMI+MPH+HR+bh,data=vo2)
summary(fit6)
fit7 <- lm(MaxVO2ML ~ Gender+MPH+HR,data=vo2)
summary(fit7)
M1 <- MaxVO2ML ~ Gender+MPH+HR
M2 <- MaxVO2ML ~ Gender+BMI+MPH+HR
Btest(models = c(H0=M1,H1=M2),data=vo2)
M3 <- MaxVO2ML ~ Gender+BMI+MPH+HR+bh
Btest(models = c(H0=M2,H1=M3),data=vo2)
M4 <- MaxVO2ML ~ Gender + BMI + MPH + HR + RPE
Btest(models = c(H0=M2,H1=M4),data=vo2)
fit8 <- lm(MaxVO2ML ~ Gender+BMI+MPH+HR,data=vo2)
summary(fit8)
fit9 <- lm(MaxVO2ML ~ Gender + BMI + MPH + HR + RPE, data=vo2)
summary(fit9)
fit10 <- lm(MaxVO2ML ~ Gender + BMI + MPH + HR + RPE + mh, data=vo2)
summary(fit10)
